spring:
  jpa:
    hibernate:
      ddl-auto: validate
    properties:
      hibernate:
        show_sql: false
        format_sql: false

jwt:
  expiration-minutes: 15

nginx:
  require-proxy: true

chirp:
  rate-limit:
    ip:
      apply-limit: true
  web-socket:
    allowed-origins: ${ALLOWED_ORIGINS:http://localhost:${server.port}}
