spring:
  jpa:
    hibernate:
      ddl-auto: validate
    properties:
      hibernate:
        show_sql: false
        format_sql: false

logging:
  level:
    lt.vitalijus.chirp.infra.rate_limiting: DEBUG

jwt:
  expiration-minutes: 15

nginx:
  require-proxy: true  # TODO: Fix trusted IPs and set back to true

chirp:
  rate-limit:
    ip:
      apply-limit: true
  web-socket:
    allowed-origins: "https://chirp.vitalijus.lt"
