server:
  port: 8089

spring:
  application:
    name: chirp

  datasource:
    url: ${DATABASE_URL_IPV4}
    username: ${DATABASE_USER_IPV4}
    password: ${DATABASE_PASSWORD}
    driver-class-name: org.postgresql.Driver

    hikari:
      pool-name: chirp-hikari
      maximum-pool-size: 5
      minimum-idle: 2
      connection-timeout: 20000
      idle-timeout: 300000
      max-lifetime: 12000000
      validation-timeout: 5000

      data-source-properties:
        prepareThreshold: 5
        preparedStatementCacheQueries: 256
        preparedStatementCacheSizeMiB: 5

        tcpKeepAlive: true
        socketTimeout: 30
        connectTimeout: 10

  jpa:
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
  
  profiles:
    include:
      - user
      - notification
      - security
    group:
      dev:
        - notification-dev
      prod:
        - notification-prod

supabase:
  url: "https://lpxhbjjlyomsbeepyogu.supabase.co"
  service-key: ${SUPABASE_SERVICE_KEY}

firebase:
  credentials-path: "classpath:firebase-credentials/chirp-firebase-adminsdk.json"