spring:
  jpa:
    hibernate:
      ddl-auto: validate
    properties:
      hibernate:
        show_sql: false
        format_sql: false

jwt:
  expiration-minutes: 15

nginx:
  require-proxy: false
  trusted-ips:
    - 127.0.0.0/8

chirp:
  rate-limit:
    ip:
      apply-limit: true
  web-socket:
    allowed-origins: "https://chirp.vitalijus.lt"
